version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      via-libraries:
        patterns:
          - "com.viaversion:viaversion-common"
          - "com.viaversion:viabackwards-common"
          - "com.viaversion:viarewind-common"
          - "com.viaversion:viaaprilfools-common"
          - "net.raphimc:ViaLegacy"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
