modLoader="javafml" #mandatory
loaderVersion="[2,)" #mandatory


license="GPL-3.0 license"
issueTrackerURL="https://github.com/ViaVersion/ViaForge/issues"
showAsResourcePack=false

[[mods]]
modId="viaforge"
version="1.21.5"
displayName="ViaForge"
displayURL="https://github.com/FlorianMichael"
logoFile="icon.png"
credits="Github contributors"
authors="FlorianMichael/EnZaXD"
description="description"
