modLoader="javafml"
loaderVersion="[2,)"

license="GPL-3.0 license"
issueTrackerURL="https://github.com/ViaVersion/ViaForge/issues"
showAsResourcePack=false

[[mods]]
modId="viaforge"
version="${version}"
displayName="ViaForge"
displayTest = "IGNORE_ALL_VERSION"
displayURL="https://github.com/florianreuth"
logoFile="icon.png"
credits="Github contributors"
authors="Florian Reuth (EnZaXD)"
description="{description}"

[[mixins]]
config = "mixins.viaforge.json"
