name: ViaForge CI
on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        java: ["8"]
        os: ["ubuntu-22.04"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Make Gradle wrapper runnable on Unix
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew shadowJar
      - name: Upload Build Artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '8' }}
        uses: actions/upload-artifact@v3
        with:
          name: ViaForge-1.12.2
          path: viaforge-mc112/build/libs/
